name: safetypass_app
description: "safetypass dev app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^3.5.0

  cupertino_icons: ^1.0.6

  # status manage
  provider: ^6.0.5
  #router
  go_router: ^13.1.0
  #svg
  flutter_svg: ^2.0.10+1
  #env
  flutter_dotenv: ^5.2.0
  # 직렬화 Freezed
  freezed_annotation: ^2.0.3
  #모델 만들기
  json_annotation: ^4.9.0
  #DI
  get_it: ^7.7.0
  # network
  dio: ^5.3.2
  #csv
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.0.3
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path: "assets/images/init-character.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/

  fonts:
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
    - family: PretendardExtraBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
    - family: AlkatraSemiBold
      fonts:
        - asset: assets/fonts/Alkatra-SemiBold.ttf
    - family: Noto Serif Malayalam
      fonts:
        - asset: assets/fonts/NotoSerifMalayalam-Regular.ttf
